### ISSUE TITLE
Allow for the parsing of HTML greatethan/lessthan symbols in the XML Test Schema

### ISSUE THREAD

**Issue by magterskine** [magento/magento2-functional-testing-framework#106]
Currently, out XML parsing errors where the symbols "<" or ">" are used.
These symbols can be useful to assert with html elements.

### Expected result
* Modify the XML Parser (?) so it allows the parsing of HTML in Test XML actions, such as but not limited too:
** seeInPageSource
*** {{<seeInPageSource html="<h1></h1>" mergeKey="seeInPageSource"/>}}
** seeInSource
*** {{<seeInSource html="<h1></h1>" mergeKey="seeInSource"/>}}
** dontSeeInSource
*** {{<dontSeeInSource html="<h1></h1>" mergeKey="dontSeeInSource"/>}}### Preconditions

**Comment by tomreece** [comment]
Closing this as solved by https://jira.corp.magento.com/browse/MQE-1639
