### ISSUE TITLE
Do not allow for $data.key$ replacement in selector parameters

### ISSUE THREAD

**Issue by magterskine** [magento/magento2-functional-testing-framework#107]
Given the following element and test action:

//In AdminLoginFormSection
--
```
<element name="paramelement" type="button" selector="{{var1}}" parameterized="true"/>
<click stepKey="1" selector="{{AdminLoginFormSection.paramelement('SomeString.$data.key$.after')}}"/>
```

The Generator actually outputs

```
$I->click("SomeString." . $data->getCreatedDataByName('key') . ".after");
```

We do not want to allow this kind of nested replacement, as this kind of replacement can't be replicated nested xml.data references (and is a door to recursive replacement we do not want to be open).

### Expected result
ActionObject detects when a user is attempting to input $data.key$ references inside arguments for parameterized selectors/urls and throws a warning/dies.

**Comment by tomreece** [comment]
Closing this as no longer relevant. We already have some parameterized selectors in the code base that make use of replacement. So we cannot and should not implement this.
