### ISSUE TITLE
assertEquals parsing does not correctly evaluate type "variable" for actualResult

### ISSUE THREAD

**Issue by nathanjosiah** [magento/magento2-functional-testing-framework#130]
`assertEquals` outputs `actualResult` with a prefixed "$" rather than actually parsing the value.

### Preconditions
MFTF 2.2

### Steps to reproduce

Following the example in [the docs](https://devdocs.magento.com/guides/v2.2/magento-functional-testing-framework/release-2/test/assertions.html)

```xml
<!-- Grab a value from the page using any grab action -->
<grabTextFrom selector="#elementId" stepKey="stepKeyOfGrab"/>

<!-- Ensure that the value we grabbed matches our expectation -->
<assertEquals message="This is an optional human readable hint that will be shown in the logs if this assert fails." stepKey="assertEquals1">
   <expectedResult type="string">Some String</expectedResult>
   <actualResult type="variable">A long assert string {$stepKeyOfGrab} with an embedded variable reference.</actualResult>
</assertEquals>
```

### Expected result

```php
$stepKeyOfGrab = $I->grabTextFrom("#elementId");
$I->assertEquals("Some String", 'A long assert string ' . $stepKeyOfGrab. ' with an embedded variable reference.', "This is an optional human readable hint that will be shown in the logs if this assert fails.");
```

### Actual result

```php
$stepKeyOfGrab = $I->grabTextFrom("#elementId");
$I->assertEquals("Some String", $A long assert string {$stepKeyOfGrab} with an embedded variable reference., "This is an optional human readable hint that will be shown in the logs if this assert fails.");
```

**Comment by KevinBKozan** [comment]
@nathanjosiah This is actually a devdocs issue, The `type` given to `actualResult` just needs to be `type="string"`. This allows it to resolve properly:
`$I->assertEquals("Some String", "A long assert string {$stepKeyOfGrab} with an embedded variable reference.", "This is an optional human readable hint that will be shown in the logs if this assert fails.");`

I've opened a devdocs PR to fix this:
https://github.com/magento-pangolin/devdocs/pull/2
