### ISSUE TITLE
Allow running tests for modules installed in Magento instance via vendor directory. 

### ISSUE THREAD

**Issue by lazyguru** [magento/magento2-functional-testing-framework#162]
Allow running tests for modules installed in Magento instance via vendor directory. 

### Preconditions
1. Install Magento 2.2.x or later
2. Install custom module using composer (so module is installed under MAGENTO_BP/vendor
3. Custom module contains tests under Test/Mftf
4. Mftf is installed and configured per DevDocs instructions

### Steps to reproduce
1. cd MAGENTO_BP/dev/tests/acceptance
2. vendor/bin/robo generate:tests

### Expected result
1. Tests from custom module are generated under MAGENTO_BP/dev/tests/acceptance/tests/functional/Magento/FunctionalTest/_generated/default

### Actual result
1. Custom module is completely ignored as MAGENTO_BP/vendor is not parsed as a location for tests.  Only the following paths are parsed:
a. MAGENTO_BP/app/code/
b. MAGENTO_BP/dev/tests/acceptance/vendor
c. MAGENTO_BP/dev/tests/acceptance/tests/functional/Magento/FunctionalTest

**Comment by lazyguru** [comment]
As a workaround, setting `CUSTOM_MODULE_PATHS=<MAGENTO_BP>/vendor/<vendor_name>/<module>/Test/Mftf` in `.env` does seem to allow tests to run.  However, ideally this should not be needed

**Comment by snohe** [comment]
@lazyguru, thanks for submitting this Github issue. We have created MQE-1124 to track this in our internal ticketing system.

**Comment by aljcalandra** [comment]
Resolved in magento/magento2-functional-testing-framework/pull/228
