### ISSUE TITLE
[Question] executeJS action

### ISSUE THREAD

**Issue by mmularski** [magento/magento2-functional-testing-framework#214]
Hello
I need help with `<executeJS>` action.
Is it possible to get value from executed JS via `<executeJS>` action and pass it in different action?

I need something like example attached in documentation `$myVar = $I->executeJS('return $("#myField").val()');`
I know about `<grabTextFrom>` action, but before grabbing value I need to process it.

**Comment by KevinBKozan** [comment]
@mmularski Yes it is possible to grab the value from an `<executeJS>` action.
The code block provided by @ameysar is correct, but just to add onto it, you can use the returned data like you would any `grab*` action:
```
<grabValueFrom stepKey="grabbedText" selector=".selector"/>
<comment userInput="Here is my grabbed text: {$grabbedText}" stepKey="showThatWeGrabbedIt"/>
```

**Comment by mmularski** [comment]
@ameysar @KevinBKozan following code does not work for me:

`<executeJS function="return (jQuery('.page-title').text().substring(1))" stepKey="invoiceNumber2"/>
<fillField userInput="$invoiceNumber2" selector="{{StorefrontCustomerMyOrdersSection.invoiceNumberFilter}}" stepKey="fillInvoiceNumber"/>
`

It generates PHP like:
`		$I->executeJS("return (jQuery('.page-title').text().substring(1))");
		$I->fillField("#invoice-number", "$invoiceNumber2");
`

but `$invoiceNumber2` is not set. I need something like:
`		$invoiceNumber2 = $I->executeJS("return (jQuery('.page-title').text().substring(1))");
		$I->fillField("#invoice-number", "$invoiceNumber2");
`

**Comment by ameysar** [comment]
@mmularski which version of **magento2-functional-testing-framework** do you use ? Provided example works on 2.2.0

**Comment by mmularski** [comment]
`vendor/bin/robo build:project` does not fix the problem.
removing vendor/, composer.lock and `composer install` command too. Everything I've done with documetation.

```
ERROR: Use of undefined constant MAGENTO_BP - assumed 'MAGENTO_BP' 
in /home/www/m2contribution/www/dev.magento.pl/dev/tests/acceptance/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php:225

```
