### ISSUE TITLE
Cannot generate tests

### ISSUE THREAD

**Issue by kowalikus** [magento/magento2-functional-testing-framework#254]
Running command `vendor/bin/mftf generate:tests` gets error.

### Preconditions

1. Magento version 2.3.0-beta23
2. Mftf version 2.3.8

### Steps to reproduce

1. Run vendor/bin/mftf generate:tests 

### Expected result

1. Tests should been generated

### Actual result

1. Error in console with message: `In Dom.php line 274:

  More than one node matching the query: /tests/test[@name='StorefrontConfigurableProductBasicInfoTest']/before/actionGroup[@stepKey='createProduct']/argument`

**Comment by KevinBKozan** [comment]
@kowalikus thank you for submitting this bug! 
Are you using the MFTF version embedded in the `2.3.0-beta23` or are you using a standalone pull of MFTF to generate the tests?

**Comment by tomreece** [comment]
Closed due to inactivity.
