### ISSUE TITLE
Inconsistent Code Sniffer ruleset between Magento and MFTF

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#265]
For Magento contribution we are expected to follow several code style rules defined by PHP Code Sniffer ruleset: https://github.com/magento/magento2/blob/c934ccc3bfa1a79b78052c61a5478eaf77de7029/dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml

For Magento Functional Testing Framework the ruleset (https://github.com/magento/magento2-functional-testing-framework/blob/95aa636421933fe23338acb98089408ce7637a63/dev/tests/static/Magento/ruleset.xml) for code is different, inconsistent to the Magento one.

### Expected result
1. Ruleset should be consistent across all Magento projects.

<img width="1680" alt="zrzut ekranu 2018-11-5 o 09 09 16" src="https://user-images.githubusercontent.com/1639941/47985637-94dffe00-e0da-11e8-86dd-2230cb6caf2e.png">
<img width="1680" alt="zrzut ekranu 2018-11-5 o 09 09 27" src="https://user-images.githubusercontent.com/1639941/47985643-9b6e7580-e0da-11e8-97e4-a8d7d63d6021.png">

The most irritating rule for MFTF is...

<img width="589" alt="zrzut ekranu 2018-11-3 o 15 46 36" src="https://user-images.githubusercontent.com/1639941/47969273-58c68200-e075-11e8-8b17-4134a124bc49.png">

**Comment by KevinBKozan** [comment]
@lbajsarowicz Thanks for reporting this! At some point in the past we were forced to update our codesniffer rulesets, and tried to match whatever was in the current `develop` branch (which may or may not have included the above irritating rule).

I am going to create a ticket internally to fix this, as I agree that our standards should allign with the main application..

**Comment by ihor-sviziev** [comment]
https://github.com/magento/marketplace-eqp - here is one more set of rules. Different rule set.

**Comment by ravmenon** [comment]
@ihor-sviziev we do plan to consolidate the EQP rules with core M2 and possibly others - there is a plan in the works. Will  share more more details once we finalize it.

**Comment by tomreece** [comment]
Internal ticket
https://jira.corp.magento.com/browse/MQE-1341

**Comment by lbajsarowicz** [comment]
@tomreece / @okolesnyk - Support for PHP 7.0 and 7.1 should be dropped.

**Comment by lbajsarowicz** [comment]
Magento codebase is too different from MFTF, so the full set of rules does not make sense.

We should follow **most** of the PHP rules from `magento/magento2` repository, but drop the ones specific for Magento.
