### ISSUE TITLE
Cannot use entity data key as an argument of action group if that data key is used in parameterized selector

### ISSUE THREAD

**Issue by dmitriyprime** [magento/magento2-functional-testing-framework#277]
### Preconditions

Install Magento 2.2.x or later
Mftf is installed and configured per DevDocs instructions (version 2.3.11)

### Steps to reproduce

1. Create action group that is using parameterized selector with its argument in that selector. For example:

`<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
    <actionGroup name="AdminDeleteSharedCatalogActionGroup">
        <arguments>
            <argument name="sharedCatalogName"/>
        </arguments>
        <click selector="{{AdminSharedCatalogsSection.select}}" stepKey="clickSelectButton"/>
        <click selector="{{AdminSharedCatalogsSection.delete('sharedCatalogName')}}" stepKey="clickDeleteAction"/>
        <waitForElementVisible selector="{{AdminConfirmationModalSection.ok}}" stepKey="waitForConfirmationModalToAppear"/>
        <click selector="{{AdminConfirmationModalSection.ok}}" stepKey="confirmDeleteSharedCatalog"/>
        <see selector="{{AdminMessagesSection.success}}" userInput="The shared catalog was deleted successfully." stepKey="seeSuccessMessage"/>
    </actionGroup>
</actionGroups>`

2. Create parametrized selector mentioned at first step in [AdminSharedCatalogsSection](https://github.com/magento/magento2b2b/blob/1.0-develop/app/code/Magento/SharedCatalog/Test/Mftf/Section/AdminSharedCatalogsSection.xml):

   `<element name="delete" type="button" selector="//div[text()='{{sharedCatalogName}}']/parent::td//following-sibling::td[@class='data-grid-actions-cell']//a[text()='Delete']" timeout="30" parameterized="true"/>`

3. Use action group mentioned at first step in your test with argument value as entity key:

`<amOnPage url="{{AdminSharedCatalogIndexPage.url}}" stepKey="goToAdminSharedCatalogIndexPage1"/>
        <actionGroup ref="AdminDeleteSharedCatalogActionGroup" stepKey="deleteSharedCatalog">
            <argument name="sharedCatalogName" value="{{NewSharedCatalog.name}}"/>
        </actionGroup>`

### Expected result

The result in generated test should be the next:

`$I->click("//div[text()='New Shared Catalog" . msq("NewSharedCatalog") . "']/parent::td//following-sibling::td[@class='data-grid-actions-cell']//a[text()='Delete']");`

### Actual result

The result in generated test is the next:

`$I->click("{{AdminSharedCatalogsSection.delete('New Shared Catalog" . msq("NewSharedCatalog") . "')}}");`

**Comment by petrovsa** [comment]
Complain selectors follow as: a[contains(text(), 'SomeTextHere')]"/ This is best practices for Mftf

**Comment by soumyau** [comment]
Action Group arguments must specify type attribute ref: https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#113-functional-testing [section 11.3.5.2] 
In this case, modify:
` <arguments> <argument name="sharedCatalogName"/>` to  
`<arguments> <argument name="sharedCatalogName" type= "string"/>` 
and you should be able to see the expected substitution.
