### ISSUE TITLE
Reference secret data outside of fill field actions

### ISSUE THREAD

**Issue by lazyguru** [magento/magento2-functional-testing-framework#280]
Currently you can only reference credentials (secret data) in fill field actions.  Instead, it should be possible to access this data from magentoCLI calls as well

### Preconditions
1. Create a credentials file and add values to it

### Steps to reproduce
1. In a <before> block (either in a test or in a suite) add `<magentoCLI command="config:set some/secret/password {{_CREDS.mySecretPassword}}" stepKey="SetSecretPassword"/>` 
2. Attempt to generate the suite/test `bin/mftf generate:suite MySuite`

### Expected result
1. Tests should be generated

### Actual result
1. Error message:
```
In ActionMergeUtil.php line 112:

  You cannot reference secret data outside of fill field actions


generate:suite [-r|--remove] [--] <suites> (<suites>)...
```

**Comment by tomreece** [comment]
As of MFTF 2.4.3 this request has been resolved.

Internal tickets for reference:
https://jira.corp.magento.com/browse/MQE-1368
https://jira.corp.magento.com/browse/MQE-1427
