### ISSUE TITLE
Can't run tests without a store having "default" store code

### ISSUE THREAD

**Issue by careys7** [magento/magento2-functional-testing-framework#31]
### Preconditions

1. Magento 2.2.2
2. Manually install MFTF into dev folder (using magento2 2.2-develop latest)

### Steps to reproduce

1. Setup Magento store(s) without having one with a store code "default" 
2. Run tests as follows

```bash
$ vendor/bin/robo example -v
```

### Expected result

1.  POST request issued to /rest/V1/integration/admin/token 

### Actual result

1. POST request issued to `/rest/default/V1/integration/admin/token`, causes 404 error

```
172.18.0.6 - - [31/Jan/2018:05:55:37 +0000] "POST /rest/default/V1/integration/admin/token HTTP/1.1" 404 1883 "-" "Symfony BrowserKit"
```

Would be good to either define a different store code to use for the REST API requests, or just to omit it and let the Magento WebAPI's request processor handle the logic (it chooses the default store's code when omitted).

**Comment by snohe** [comment]
Thanks for your report, @careys7.  We have created MQE-743 to track this issue.
