### ISSUE TITLE
Getting undefined index SampleData error on generate tests command

### ISSUE THREAD

**Issue by ranahemantkumar** [magento/magento2-functional-testing-framework#312]
I have installed vanilla magento2.6 version. Open terminal, cd to <magento_root>/dev/tests/acceptance/ , run composer install and vendor/bin/robo build:project, changed settings in .env file to point to local magento2 installation. Then on running vendor/bin/robo generate:tests, I am getting error: Fetching version information from http://127.0.0.1/careshop2/magento_version
PHP Notice:  Undefined index: SampleData in C:\xampp2\htdocs\careshop2\dev\tests\acceptance\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Util\ModuleResolver.php on line 309

Notice: Undefined index: SampleData in C:\xampp2\htdocs\careshop2\dev\tests\acceptance\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Util\ModuleResolver.php on line 309
 [error]  Could not resolve entity reference {{StorefrontCustomerOrderSection.isMyOrdersSection}} in Test "StorefrontRedirectToOrderHistory" in Test "StorefrontRedirectToOrderHistory"
ERROR: Undefined index: SampleData
in C:\xampp2\htdocs\careshop2\dev\tests\acceptance\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Util\ModuleResolver.php:309

### Preconditions

1.  magento version 2.2.6
2. magento2-functional-testing-framework version 2.2.0

### Steps to reproduce

1. Install magento 2.2.6
2. run terminal and cd to dev/tests/acceptance, Run composer install , command run completed successfully.
3. Run vendor/bin/robo build:project, command run completed successfully. Edit .env settings to point to magento2 with correct url, admin name, adminusername, admin password, Save file
4. Run selenium server on another terminal with chrome driver and selenium server jar both kept at same location. Output selenium server up and running on port 4444
5. Try to run vender/bin/robo generate:tests , it gives undefined index sampleData error 

### Expected result

1. Test should be generated successfully 

### Actual result

1. Got below error:
Fetching version information from http://127.0.0.1/careshop2/magento_version
PHP Notice:  Undefined index: SampleData in C:\xampp2\htdocs\careshop2\dev\tests\acceptance\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Util\ModuleResolver.php on line 309

Notice: Undefined index: SampleData in C:\xampp2\htdocs\careshop2\dev\tests\acceptance\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Util\ModuleResolver.php on line 309
 [error]  Could not resolve entity reference {{StorefrontCustomerOrderSection.isMyOrdersSection}} in Test "StorefrontRedirectToOrderHistory" in Test "StorefrontRedirectToOrderHistory"
ERROR: Undefined index: SampleData
in C:\xampp2\htdocs\careshop2\dev\tests\acceptance\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Util\ModuleResolver.php:309

This error is platform independent as I have tried in another system with ubuntu.
Also I tried not following step4 (from above steps I mentioned) and then to run generate:tests but still got same error.

**Comment by KevinBKozan** [comment]
@ranahemantkumar, I think the actual error that is being thrown here is not related to the `Undefined index` Notice (notices are by definition only a notice, not a runtime error). I pulled `tags/2.2.6` from Magento2CE and did not get that notice or error though, strangely.

I do see in your error message though that there is `[error] Could not resolve entity reference {{StorefrontCustomerOrderSection.isMyOrdersSection}} in Test "StorefrontRedirectToOrderHistory"`, that looks like the real culprit.
Is the following file in your `2.2.6` installation `magento2ce/app/code/Magento/Customer/Test/Mftf/Section/StorefrontCustomerOrderSection.xml`?

**Comment by ranahemantkumar** [comment]
Hey @KevinBKozan 
Thanks for looking into it.
Yup its first a notice but same thing is shown in errors right below it.
I don't have Magento folder inside my app/code or do you mean any other location.
Also want to add I have tested it with 3 magento2.6 installations (two of them being vanilla magento)

**Comment by KevinBKozan** [comment]
@ranahemantkumar Apologies, yes a composer installation would have it living somewhere under `vendor/magento`. If you can search for the file `StorefrontCustomerOrderSection.xml` in `vendor` it may help in finding the issue.
The reason I'm asking about that file is because `StorefrontCustomerOrderSection` lives there, which is where the error is coming from. If that file is nowhere in vendor that will probably be the source of errors.

I will try composer installing `2.2.6` and `2.2.7` to see if I can reproduce these errors.

**Comment by ranahemantkumar** [comment]
@KevinBKozan 
File is there under vendor/magento/module-customer/Test/Mftf/Section     StorefrontCustomerOrderSection.xml  , below is content of file:

<sections xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../../../../../../../dev/tests/acceptance/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Page/etc/SectionObject.xsd">
    <section name="StorefrontCustomerOrderSection">
        <element name="isMyOrdersSection" type="text" selector="//*[@class='page-title']//*[contains(text(), 'My Orders')]"/>
        <element name="productCustomOptions" type="text" selector="//strong[contains(@class, 'product-item-name') and normalize-space(.)='{{var1}}']/following-sibling::*[contains(@class, 'item-options')]/dt[normalize-space(.)='{{var2}}']/following-sibling::dd[normalize-space(.)='{{var3}}']" parameterized="true"/>
        <element name="productCustomOptionsFile" type="text" selector="//strong[contains(@class, 'product-item-name') and normalize-space(.)='{{var1}}']/following-sibling::*[contains(@class, 'item-options')]/dt[normalize-space(.)='{{var2}}']/following-sibling::dd[contains(.,'{{var3}}')]" parameterized="true"/>
    </section>
</sections>

**Comment by KevinBKozan** [comment]
@ranahemantkumar I believe I know the cause then. MFTF `2.2.0` did not include full support for parsing any tests under `vendor`, and it's not being able to find that file.

I would reccomend either:
* Using Magento `2.2.7` instead, which uses MFTF `2.3.x` as a root dependency
* [Set up MFTF as standalone](https://devdocs.magento.com/mftf/2.3/getting-started.html#set-up-a-standalone-mftf) and use latest MFTF version for parsing tests.

I'm confident that either option would solve your issue, let me know if the problem persists.

**Comment by ranahemantkumar** [comment]
@KevinBKozan 
I ll try above recommendations and let you know outcome anyways.
Again, Thanks for looking into it.

**Comment by soumyau** [comment]
Hi @ranahemantkumar Apologies for the late response. Have you tried this with the latest MFTF release 2.5.2?

**Comment by soumyau** [comment]
Closing this issue due to no response. Please feel free to open this ticket if the issue persists with latest MFTF.
