### ISSUE TITLE
Failed to generate the tests

### ISSUE THREAD

**Issue by RajuA3112** [magento/magento2-functional-testing-framework#315]
When i tried to generate the tests using vendor/bin/mftf generate:tests, MFTF is generating only one test,that is "testName":"AdminResetCustomerPasswordTest.

Showing                                                                                                                                        
  Could not find ActionGroup by ref "AdminUpdateCustomerGroupByEmailActionGroup" in Element "before"                                         
  /var/www/html/magentoone/vendor/magento/module-inventory-admin-ui/Test/Mftf/Test/AdminOrderCreatedWithConfigurableProductWithSwatchAttrib  
  uteViaTheAdminTest.xml 

### Preconditions

PHP 7.2.15
selenium-server-standalone-3.141.59 and chrome driver
Browser is chrome Version 72.0.3626.119 
Magento 2.3
Magento Functional Testing Framework version 2.3

### Steps to reproduce

1. vendor/bin/mftf generate:tests

### Expected result

1. Generate Tests Command Run

### Actual result

1. DEPRECATION: Test AdminResetCustomerPasswordTest is missing required annotations.{"testName":"AdminResetCustomerPasswordTest","missingAnnotations":"title"}

In TestGenerator.php line 229:
                                                                                                                                             
  Could not find ActionGroup by ref "AdminUpdateCustomerGroupByEmailActionGroup" in Element "before"                                         
  /var/www/html/magentoone/vendor/magento/module-inventory-admin-ui/Test/Mftf/Test/AdminOrderCreatedWithConfigurableProductWithSwatchAttrib  
  uteViaTheAdminTest.xml

**Comment by sshrewz** [comment]
Hi @RajuA3112 - apologies for the late response.  Have you tried using our latest MFTF release?

**Comment by soumyau** [comment]
Closing the issue due to no response, feel free to open a new ticket if the issue persists with latest MFTF. Thank you.
