### ISSUE TITLE
Suite generation defect under Magento 2.3.1

### ISSUE THREAD

**Issue by powli** [magento/magento2-functional-testing-framework#329]
### Preconditions
1. PHP 7.2 
2. magento/project-enterprise-edition (2.3.1)
3. magento/magento2-functional-testing-framework (2.3.14)
4. installed extension with it's own MFTF suite

### Steps to reproduce
1. `vendor/bin/mftf build:project`
2. `vendor/bin/mftf generate:suite MyCustomSuite`

### Expected result
1. Only the tests in the suite and the action groups / sections / pages it is using should be generated

### Actual result
1. All available tests are being generated

The expected result can be achieved using the following preconditions (default installation):
magento/project-enterprise-edition (2.3.0)
magento/magento2-functional-testing-framework (2.3.11)

**Comment by powli** [comment]
## Update: 
@okolesnyk looked into it with the following findings:

> The thing is that this is not a MFTF issue. Problem is in Klarna tests. Even if you generate only your suite we still read all the Tests and all xml files to filter them by your custom suite. And the thing is that 3 Klarna test entities violates XSD schema.
> The are 2 options how you can solve this issue:
>1. Disable `klarna/module-kp` component by running `bin/magento module:disable Klarna_Kp`
>2. Fix 3 Klarna Test files:
>   - `vendor/klarna/module-kp/Test/Mftf/Data/KpSalesRuleData.xml` comment or remove `<data key="use_auto_generation">false</data>`
>   - `vendor/klarna/module-kp/Test/Mftf/ActionGroup/KpAddCouponActionGroup.xml` make unique stepKey by replacing `<wait stepKey="openCouponFieldWait" time="5"/>`  L#21 to `<wait stepKey="openCouponFieldWait1" time="5"/>`
>   - `vendor/klarna/module-kp/Test/Mftf/ActionGroup/KpAddToCartActionGroup.xml` replace one of `productWait3` stepKeys to something unique in scope of file.

**Comment by powli** [comment]
@fooman: this issue actually fits the problem you mentioned yesterday during the call: core bundled modules within the composer installation killing the test process for us.

**Comment by fooman** [comment]
@powli indeed - I just cross post the twitter conversation here https://twitter.com/foomanNZ/status/1110672512591884288
