### ISSUE TITLE
actionGroup ProductSetAdvancedPricing does not work for Fixed Price

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2-functional-testing-framework#352]
### Preconditions

1. Magento 2.3.0

### Steps to reproduce

1. Create a custom MFTF Test and use the action group ProductSetAdvancedPricing with argument price = "Fixed"
2. Run the test

### Expected result

1. This should normally fill the advanced price form with a fixed discount amount.

### Actual result

1. The test fails and does not find the selector `[name='product[tier_price][0][percentage_value]']`

In magento/module-catalog/Test/Mftf/ActionGroup/AdminProductActionGroup.xml line 205 the amount is inserted into the field with the selector `{{AdminProductFormAdvancedPricingSection.productTierPricePercentageValuePriceInput('0')}}`
But this field only exists, when the price argument is set to "Discount". As soon as this is "Fixed", the field is called `product[tier_price][0][price]`.
So either the action group should be renamed to "ProductSetAdvancedPricingDiscountAmount" and the price removed or there should be a condition check which decides which field to fill.

**Comment by tomreece** [comment]
Hi @norgeindian thank you for the report. However you're mentioning an action group that lives in the Magento2 repository, not in this MFTF repository. I would suggest moving your issue to https://github.com/magento/magento2

Thanks!

**Comment by norgeindian** [comment]
Hi @tomreece,
that is exactly what I did a few days before I opened this issue (see https://github.com/magento/magento2/issues/22879) where I was told to open it here...

Please be so kind and discuss internally who is responsible for that, so this gets solved.

Thanks !

**Comment by tomreece** [comment]
I investigated further and discovered that someone has created this action group:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminProductActionGroup.xml#L345

`ProductSetAdvancedTierFixedPricing`

Can you make use of this?

**Comment by norgeindian** [comment]
@tomreece, yes, this looks good. But then the original actionGroup should be renamed to ProductSetAdvancedTierDiscountPricing, so it gets obvious what this actionGroup actually does and the price argument should be removed. Shall I open a pull request in the Magento repository or what would be the correct way to go?

**Comment by tomreece** [comment]
@norgeindian 

I don't want to discourage you from opening the pull request, but renaming an existing action group is considered a breaking change because some other extensions may depend on that action group to exist.

I don't expect this change to be possible.
@okolesnyk what do you think?

**Comment by jilu1** [comment]
@norgeindian 
Now you can deprecated an action group if it's outdated using "deprecated" attribute. Close this issue.
