### ISSUE TITLE
[Discussion] MFTF runs the tests in parallel

### ISSUE THREAD

**Issue by vantruongt2** [magento/magento2-functional-testing-framework#378]
### Question
How can we run the tests in parallel with MFTF

**Comment by tomreece** [comment]
In our internal CICD pipeline we parallelize using custom pipeline code. The gist of it is:

1. generate tests with `generate:tests --config parallel`
2. A whole bunch of `group.txt` files will be created in the `../generated/groups` directory
3. Each `group.txt` file contains a subset of tests.
4. We spawn many nodes and run different group files on different nodes.

This is a high level overview. It's quite a bit more complicated and probably expensive to set up such environments.

We are working on some documentation and environments to be released in the future that may help you, but I do not know when this will be ready.

Does this help? Feel free to continue discussion/questions! Thanks!

**Comment by sshrewz** [comment]
@vantruongt2 - since we have not heard back from you, we will go ahead and close this ticket.  Feel free to reach out to use if you have any other questions.

**Comment by xsanz** [comment]
I think the question here is How
'We spawn many nodes and run different group files on different nodes.' ?
