### ISSUE TITLE
Can not generate:test in Magento 2.3

### ISSUE THREAD

**Issue by ThiKiet** [magento/magento2-functional-testing-framework#383]
When I run this command **vendor/bin/mftf generate:tests its show me this error** 

![image](https://user-images.githubusercontent.com/44836421/61429624-38afc800-a951-11e9-82c5-56f61dd2f3fd.png)

How can I fix it?

**Comment by tomreece** [comment]
Hi @ThiKiet sorry that it took us so long to reply. We are improving our GitHub processes now.

Are you still having this issue?

**Comment by sshrewz** [comment]
Hi @ThiKiet, since we have not heard back from you, we'll go ahead and close this issue.  Feel free to reopen or submit a new issue in case you need help.
