### ISSUE TITLE
ERROR: Line 154: Test AdminLoginTest not defined in xml

### ISSUE THREAD

**Issue by WinstonN** [magento/magento2-functional-testing-framework#387]
Hi, 

Would love to get started on MFTF - looks great!
I've installed mftf standalone, and setup my .env

When running `bin/mftf run:test AdminLoginTest` I get the error inside my Magento directory, in the log, `dev/tests/acceptance/mftf.log`

```[2019-07-20 15:35:27] Magento\FunctionalTestingFramework\Test\Handlers\TestObjectHandler.ERROR: Line 154: Test AdminLoginTest not defined in xml. [] []```

I can see this test, in `dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Backend/Test/AdminLoginTest.xml` which makes me think there is something wrong with path/test resolution on my side

Anyone seen this before?

**Comment by WinstonN** [comment]
Ah! Things started working after I added 
`TESTS_MODULE_PATH=/path/to/magento/dev/tests/acceptance/tests/functional/Magento/FunctionalTest`

Getting more error's but they're different errors 🖖 - I'm leaving my .env file here for future travelers like me 

```
MAGENTO_BASE_URL=https://www.domain.com/
MAGENTO_BACKEND_NAME=voo
MAGENTO_ADMIN_USERNAME=doo
MAGENTO_ADMIN_PASSWORD=boo
BROWSER=chrome
MODULE_WHITELIST=Magento_Framework,Magento_ConfigurableProductWishlist,Magento_ConfigurableProductCatalogSearch
DEFAULT_TIMEZONE=Pacific/Auckland

# BasePath Settings
MAGENTO_BP=/path/to/magento/
TESTS_BP=/path/to/magento/dev/tests/acceptance
TESTS_MODULE_PATH=/path/to/magento/dev/tests/acceptance/tests/functional/Magento/FunctionalTest
```
🖖

**Comment by alwinj1989** [comment]
Hi @WinstonN ,

Does it really works for you.. I am running in M2.4.1 version but seems like I am getting the same issue..
Also, we can't able to run the following command too: "vendor/bin/mftf generate:tests AdminLoginSuccessfulTest -r"

Is the above commands works for you? . If there is any solution then please let me know..

Many thanks,
Alwin Joseph

**Comment by jekajolob** [comment]
Try to use:

`vendor/bin/mftf run:test AdminLoginTest --remove --force
`
This helped for me
