### ISSUE TITLE
Section cannot use names more than once

### ISSUE THREAD

**Issue by WinstonN** [magento/magento2-functional-testing-framework#388]
Hi, 

I am getting the error: `Section cannot use names more than once`

when I run `bin/mftf run:test AdminLoginTest`
```
DEPRECATION: Test AdminCreateStoreGroupTest is missing required annotations.{"testName":"AdminCreateStoreGroupTest","missingAnnotations":"severity"}
DEPRECATION: Test AdminMoveAnchoredCategoryTest is missing required annotations.{"testName":"AdminMoveAnchoredCategoryTest","missingAnnotations":"stories"}
DEPRECATION: Test DeleteCategoriesTest is missing required annotations.{"testName":"DeleteCategoriesTest","missingAnnotations":"stories"}
DEPRECATION: Test PriceRuleCategoryNestingTest is missing required annotations.{"testName":"PriceRuleCategoryNestingTest","missingAnnotations":"stories, title"}
DEPRECATION: Test AdminConfigPaymentsSectionState is missing required annotations.{"testName":"AdminConfigPaymentsSectionState","missingAnnotations":"stories, title"}
DEPRECATION: Test StorefrontAddMultipleStoreProductsToWishlistTest is missing required annotations.{"testName":"StorefrontAddMultipleStoreProductsToWishlistTest","missingAnnotations":"stories, severity"}
DEPRECATION: Test StorefrontDeletePersistedWishlistTest is missing required annotations.{"testName":"StorefrontDeletePersistedWishlistTest","missingAnnotations":"severity"}

In ActionMergeUtil.php line 278:

  Section cannot use names more than once.
  	name: v4 is used more than once. (Parent: ProductWYSIWYGSection)
  	in file: /path/to/magento/dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Catalog/Section/AdminProductFormSection.xml.
  Exception occurred parsing action at StepKey "disableWYSYWYG"


run:test [-k|--skip-generate] [-f|--force] [-r|--remove] [--] <name> (<name>)...
```
The Wysywyg has been disabled by following the instructions here: https://devdocs.magento.com/mftf/docs/getting-started.html#set-up-a-standalone-mftf

What's confusing to me, is:

- Why is a catalog test run, when I want to run a login test?
- The error messages are not clearly showing the issue
- What does name v4 mean?

Have you seen this before?

**Comment by tomreece** [comment]
> Why is a catalog test run, when I want to run a login test?

It's being generated, not ran. MFTF parses all test files even though you only specified one test.

> The error messages are not clearly showing the issue

The error indicates that there exist more than one `<element name="v4" ../>` in the `ProductWYSIWYGSection`. Search your MFTF test files for this string: `"v4"`. Do you see multiple elements? Let us know.

> What does name v4 mean?

The error message is referring to an element named `v4`. In my codebase I see:
```
<element name="v4" type="button" selector="#category_form_description_v4"/>
```

It sounds like you may have multiple definitions of this element under the same Section object. Let us know.

**Comment by tomreece** [comment]
Hi @WinstonN are you still having issues here?
