### ISSUE TITLE
Feedback on page: /mftf/docs/test/action-groups.html

### ISSUE THREAD

**Issue by zhartaunik** [magento/magento2-functional-testing-framework#501]
Not sure but looks like information at described page is obsolete.
Here are 5 examples from magento source:

File name: AddProductToCart**ActionGroup**.xml
File name: **Admin**Product**ActionGroup**.xml
Source: &lt;actionGroup name="AddSimpleProductToCart"&gt; (name of action group is the same)
Source: &lt;actionGroup name="goToCreateProductPage"&gt; (name differs from action group and starts from the small letter)
Source: &lt;actionGroup name="FillMainProductFormByString"&gt; (name differs from action group and starts from the capital letter)

---
Phrase from guide: 
```
Every file name ends with ActionGroup, such as LoginToAdminActionGroup.
```
As I see expected phrase is:
```
Format: {Admin or Storefront}{Actions List}ActionGroup.xml, where Actions List briefly describes the what Action Group does.

Example: AdminAssignImageRolesActionGroup.xml.
```

---
Phrase from guide:
```
Begin with a Backend/ActionGroup/LoginToAdminActionGroup.xml template for the <actionGroup>:
```
Expected result: there should be no sub-folder "Backend", name should start from **Admin**.

---
And the last thing, name should start from the small letter (not sure)

**Comment by lbajsarowicz** [comment]
@zhartaunik I've updated the documentation in my Pull Request. Could you take a look and provide some feedback?

**Comment by zhartaunik** [comment]
@lbajsarowicz it suppose to be closed
