### ISSUE TITLE
Allow data access in and out of ActionGroups

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2-functional-testing-framework#502]
### Steps to reproduce
Have multiple ActionGroups pass data between each other or from ActionGroup to its calling test

### Expected result
Should be able to pass data through ActionGroups **in the scope of a single test**. I should be able to grab some attribute or value inside an ActionGroup, and later access it in the calling test using some specific format say, _ActionGroupStepKey.GrabValueStepKeyInsideActionGroup_ off the top of my head.

### Actual result
Unable to access value grabbed inside an ActionGroup, outside of it, within the scope of a single test

**Comment by KevinBKozan** [comment]
@drpayyne thanks for submitting this issue. Use case makes perfect sense, composition of mftf tests using only actionGroups is hard blocked by this.
I'll link this issue to our internal JIRA ticket for this enhancement.

**Comment by drpayyne** [comment]
Exactly, @KevinBKozan. Thanks!

**Comment by drpayyne** [comment]
Hi @KevinBKozan, is this resolved? Can this be closed?
