### ISSUE TITLE
Document full list of elements that Credentials work with

### ISSUE THREAD

**Issue by filmaj** [magento/magento2-functional-testing-framework#506]
### Preconditions

The [documentation on usage of credentials](https://devdocs.magento.com/mftf/docs/credentials.html#use-credentials-in-a-test) mentions that credentials only works with three elements: `fillField`, `createData` and `magentoCLI`. However, in my local testing, I can see it also works with `entity`/`data` elements like so:

```
    <entity name="AdobeStockConfigDataApiKey">
        <data key="path">adobe_stock/integration/api_key</data>
        <data key="value">{{_CREDS.magento/ADOBE_STOCK_API_KEY}}</data>
    </entity>
```

### Steps to reproduce

1. Visit https://devdocs.magento.com/mftf/docs/credentials.html#use-credentials-in-a-test

### Expected result

1. At a minimum also document `entity`+`data` as valid elements for use with credentials. What other elements are OK to use with credentials? And if credentials can be used with `entity`+`data`, does that essentially mean credentials can be used everywhere? (since other elements can then reference the credential information via the data elements)

### Actual result

1. See that only three elements are listed as applicable for usage with credentials: `fillField`, `createData` and `magentoCLI`.

**Comment by KevinBKozan** [comment]
@filmaj thank you for reporting this! We'll update the docs to expand a little more on `_CREDS` usage as you suggested.

**Comment by jilu1** [comment]
Devdoc PR is merged. Close issue.
