### ISSUE TITLE
Consider adding timing information to console output in tests `waitFor` actions

### ISSUE THREAD

**Issue by filmaj** [magento/magento2-functional-testing-framework#508]
This is mostly an idea for a feature request. It  would be cool if timing details were provided at different steps. I would find that useful especially for the various `waitFor` actions, especially the ones involving timeouts (to, for example, identify which wait steps are timing out).

For example, consider this output from one test I recently ran:

```
[openMediaGalleryForPage] AdminOpenMediaGalleryForPageNoEditorActionGroup
  [amOnPagePagesGrid] am on page "/backend/cms/page"
  [waitForPageLoad] wait for page load 10
  [clickAddNewPage] click "#add"
  [clickAddNewPageWaitForPageLoad] wait for page load 30
  [clickExpandContent] click "div[data-index=content]"
  [waitForInsertImageButton] wait for element visible ".scalable.action-add-image.plugin",10
  [clickInsertImage] click ".scalable.action-add-image.plugin"
  [] wait for initial media gallery load, where the gallery chrome loads (and triggers loading modal)
  [waitForMediaGalleryInitialLoad] wait for page load 10
```

It  would be cool if the actual  time spent on each step was noted, where applicable. Perhaps something like:

```
[openMediaGalleryForPage] AdminOpenMediaGalleryForPageNoEditorActionGroup
  [amOnPagePagesGrid] am on page "/backend/cms/page"
  [waitForPageLoad] wait for page load 10 (1244ms)
  [clickAddNewPage] click "#add"
  [clickAddNewPageWaitForPageLoad] wait for page load 30 (4589ms)
  [clickExpandContent] click "div[data-index=content]"
  [waitForInsertImageButton] wait for element visible ".scalable.action-add-image.plugin",10 (210ms)
  [clickInsertImage] click ".scalable.action-add-image.plugin"
  [] wait for initial media gallery load, where the gallery chrome loads (and triggers loading modal)
  [waitForMediaGalleryInitialLoad] wait for page load 10 (timed out at 10000ms)
```

The last line above could be an example of identifying a command that hit its timeout, which would help during test implementation / iteration.

Maybe even also include timing details for each actiongroup, to track how long the combined commands forming an action group took?

Just some ideas / thinking out loud. I'm curious what others think!

**Comment by jilu1** [comment]
@filmaj 
Thanks for submitting this issue. I like the idea to add timing information for test steps and action groups. I've created an internal JIRA ticket MQE-1916 for this enhancement.

**Comment by tomreece** [comment]
Discussed internally. The Allure report shows time taken for each step.
Closing this issue.
