### ISSUE TITLE
MFTF: Static test to verify that ActionGroup file contains single ActionGroup

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#520]
### Summary (*)
When submitting Magento Functional Testing Framework tests, developers usually submit several `ActionGroup` sections inside single `ActionGroup/*ActionGroup.xml` file. That's against MFTF best practices and should be avoided.

### Examples (*)
Discussion covered in https://github.com/magento/magento2/pull/25812

### Proposed solution
Static analysis to verify that ActionGroup file contains single ActionGroup and it's name is corresponding to filename.

**Comment by jilu1** [comment]
@lbajsarowicz Thank you for your suggestion! 
I have this feature request ticket MC-29336 moved to our team as MQE-1914.  We will keep you updated with progress and feedback through this PR.

**Comment by jilu1** [comment]
@lbajsarowicz Similar feature is delivered in MFTF-3.0.0-RC1. Only single ActionGroup is allowed in one file. Violation will result in generation error. Upgrade script is provided to help user to change tests into new format.
