### ISSUE TITLE
Allow running a group or test outside of a suite

### ISSUE THREAD

**Issue by lfolco** [magento/magento2-functional-testing-framework#536]
If a test belongs to a test suite, you cannot run any groups that it belongs to. For example, all the tests that are in the `Magento_Review` module are marked with the group `review`. But, one of those tests (`StorefrontVerifySecureURLRedirectReview`) belongs to the suite `SecureStorefrontURLSuite`, thereby making all the other group designations irrelevant.

### Preconditions

1. MFTF 2.5.3

### Steps to reproduce

1. Try to run a group of tests where one of the tests belongs to a suite:
```
<magento_root>/vendor/bin/mftf run:group review --remove
```

### Expected result

1.  All tests in the group `review` are run

### Actual result

Error message

```
Error Output:
================

In TestGenerator.php line 163:

  Cannot reference test configuration for generation without accompanying suite.
```

**Comment by okorshenko** [comment]
@magento I am working on this

**Comment by jilu1** [comment]
@lfolco 
I don't think we should allow running tests belong to some suites but running outside of suite context as those tests are not valid without proper before and after setup. I will close this issue but please feel free to reopen if you think otherwise.
