### ISSUE TITLE
MFTF: Lack of information on API failure (eg. <createEntity>)

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#544]
### Preconditions
1. Test that is calling Magento API (eg. `AdminVerifyCustomerAddressStateContainValuesOnceTest`)

### Steps to reproduce
1. Create required Customer Attribute
2. Try to run execute any test that creates Customer

### Expected result
1. Test fails with information about error during API Call.

### Actual result
1. ![image](https://user-images.githubusercontent.com/1639941/72194007-3e6ffd00-340c-11ea-8d18-dfe774e84591.png)
1. ![image](https://user-images.githubusercontent.com/1639941/72194014-49c32880-340c-11ea-9110-613a0f7ccaba.png)

**Comment by lbajsarowicz** [comment]
My findings: MFTF uses incorrectly the PHPUnit hooks. When _before hook fails, the failure is not being reported. Even then - _after hook is being called.

I'll design the architectural change to address the issue and avoid using hooks, just to let perform rollback of created nodes.

**Comment by jilu1** [comment]
@lbajsarowicz Thank you for reporting this issue!
Have you tested in MFTF release 2.5.4? I think we have a bug fix for a similar issue.

**Comment by lbajsarowicz** [comment]
I tried with the latest `2.4-develop` setup of Magento and latest `develop` branch of MFTF.

**Comment by lbajsarowicz** [comment]
I've made the first step - Save Request object even if API call failed.

**Comment by soumyau** [comment]
Created JIRA ticket to process this PR: https://jira.corp.magento.com/browse/MQE-2065

**Comment by jilu1** [comment]
This feature has been implemented and delivered
