### ISSUE TITLE
No information about API calls failure reason (eg. <createData>)

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#623]
### Preconditions
1. MFTF `2.5.3`

### Steps to reproduce
1. Create Product required argument
2. Perform test that uses `<createData` for creating product

### Expected result
1. Information that I haven't provided required data

### Actual result
1. MFTF tries to make screenshot :man_facepalming:

**Comment by jilu1** [comment]
@lbajsarowicz 
I think we have added API log to Allure report a while back and you have to enable it in .env. Close this issue and feel free to reopen if this is still an issue.
