### ISSUE TITLE
Bug: Skipped tests look like errors on CLI output

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#664]
### Preconditions
1. When you run PHPUnit and tests are skipped, these are marked on yellow. I'd expect the same behaviour.

### Steps to reproduce
1. Mark test as skipped
2. Execute tests

### Expected result
1. Test is marked with yellow colour

### Actual result
1. Tests are marked on red
![image](https://user-images.githubusercontent.com/1639941/77855028-27ac9b80-71ee-11ea-974f-8ad8bb219d8e.png)

**Comment by jilu1** [comment]
@lbajsarowicz Thanks for reporting the issue. I can reproduce the problem. Internal ticket https://jira.corp.magento.com/browse/MQE-2057 is created

**Comment by KevinBKozan** [comment]
https://github.com/sebastianbergmann/phpunit/issues/5133

Created bug in phpunit, closing this ticket.
