### ISSUE TITLE
Suite's <before> section runs the browser session that last to the end of suite.

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-functional-testing-framework#679]
### Preconditions
On Selenium Hub, while running Test Suites, `<before>` section initiates the Browser that is active during whole test execution.
1. MFTF 3.0-rc1
2. Magento 2.4-develop

### Steps to reproduce
1. Connect your test environment to Selenium Hub with more than 1 browser attached (otherwise tests would fail due to reached capacity).
2. Execute test Suite that contains `<before>` section
3. Watch the usage of Selenium nodes during the test

### Expected result
1. Suite's `<before> section should not start Browser session

### Actual result
1. Suite `<before>` section is opening browser session and is active during all the suite run.

**Comment by jilu1** [comment]
@lbajsarowicz Thanks for reporting this problem! I think this is fixed in MFTF 3.0.0. Can you please check?

**Comment by jilu1** [comment]
@lbajsarowicz 
Close and feel free to reopen if you still have issue
