### ISSUE TITLE
Non used Suite are executed when run any test

### ISSUE THREAD

**Issue by gabrieldagama** [magento/magento2-functional-testing-framework#704]
If I create a new Suite and don't have any tests assign to it and try to execute a test, for example:
`vendor/bin/mftf run:test AdminLoginSuccessfulTest --remove`

Even though the test above is not related to that Suite, when we execute it, it runs and gets generated as it is part of it.

This happens to any test, if we have an unused Suite whenever we execute the tests they get created and ran as it was related to that Suite.

### Steps to reproduce

1. Create a new Suite on any module, with any content inside it.
2. Run any test. For example: `vendor/bin/mftf run:test AdminLoginSuccessfulTest --remove`

### Expected result

1. The AdminLoginSuccessfulTest should be generated on the default folder and not being related to any Suite and be executed without executing the Suite steps.

### Actual result

1. The AdminLoginSuccessfulTest gets generated inside the Suite folder and the Suite gets executed before the test.

**Comment by jilu1** [comment]
@gabrieldagama I cannot reproduce this issue in MFTF 3.0.0.  Can you share the Suite xml file you used?
