### ISSUE TITLE
MFTF Standalone Can not run a test

### ISSUE THREAD

**Issue by nguyennguyen6bk** [magento/magento2-functional-testing-framework#735]
Can not run a test from MFTF Standalone

### Preconditions

1. PHP 7.3
2. Magento EE 2.3.5
3. MFTF 3.0.0-RC3 (latest)

### Steps to reproduce

1. Setup a Magento EE version 2.3.5
2. Setup an MFTF lastest version
3. Enable the Magento CLI commands
4. Remove the MFTF package dependency in Magento
5. Run a simple test by run : bin/mftf run:test AdminLoginTest
![Screenshot from 2020-06-08 16-07-17](https://user-images.githubusercontent.com/41178722/84012728-31970b80-a9a2-11ea-9871-eba2b27e5076.png)

### Expected result

MFTF-standalone can run a test with standard command line: **bin/mftf run:test AdminLoginTest** 

### Actual result

In ExceptionCollector.php line 43:                                                                                                                                                                        
  Single <suite> node per xml file. 7 found in file: /home/nguyen/Documents/htdocs/ee235-mftf-standalone/vendor/magento/module-inventory-admin-ui/Test/Mftf/Suite/msi-suite.xml                                                                                                                                                 
  Single <suite> node per xml file. 2 found in file: /home/nguyen/Documents/htdocs/ee235-mftf-standalone/vendor/klarna/module-kp/Test/Mftf/Suite/suite.xml

**Comment by soumyau** [comment]
Hi @nguyennguyen6bk, MFTF 3.0.0 is only compatible with magneto 2.4 release and above, I see you are using an older version of magento. 
We will be publishing the magneto2 version compatibilty of mftf soon here - https://devdocs.magento.com/mftf/docs/versioning.html. 

Let us know if you face issues with the correct supported versions of magento and mftf.
