### ISSUE TITLE
Provide ability to exclude test suites

### ISSUE THREAD

**Issue by naydav** [magento/magento2-functional-testing-framework#747]
**Value/COD**
     * Test writers *cannot** commit specific tests into the core codebase since their tests need a specific build environment (not suitable for running every single build)
 * Example is MySQL vs Elasticsearch specific tests; only Elasticsearch should be run every PR, mySQL should be only nightly, no way to tell MFTF to exclude the mySQL tests
 * COD is tied directly to build execution times (unecessary tests) and teams not being able to deliver specific tests

Currently, MFTF has the ability only to include test suites on configuration level. As a developer, I want to have the ability to excludes some suites from the test run. https://devdocs.magento.com/mftf/docs/commands/mftf.html#generatetests

**AC:**
 * Introduce new `--exclude` flag
             * Takes in identical json to `--tests` flag
             * Prevents generation of tests/suites in configuration passed in
 * Jenkins/Build Work
             * Introduce new MFTF Advanced Parameter `MFTF*CUSTOM_EXCLUDE*CONFIG`
                 * Passed in directly
             * Alter `generate:tests` to include above parameter during build runtime

Internal ticket: MQE-1781

**Comment by jilu1** [comment]
Previous internal Jira ticket MQE-1781 is closed as `won't do`. I will bring up this issue again and see if this can be added in the `--filter` category.

**Comment by jilu1** [comment]
Internal ticket https://jira.corp.magento.com/browse/MQE-2240 is cloned from MQE-1781.
