### ISSUE TITLE
PHPUnit\Framework\Exception Undefined offset: 43 on running the mftf default tests

### ISSUE THREAD

**Issue by rajateshr** [magento/magento2-functional-testing-framework#757]
Details:Chrome driver version: 83,Mftf version: Magento Functional Testing Framework CLI 2.6.5,PHP 7.2.31,Magento version:2.3.5-p1, Selenium Server version is:selenium-server-standalone-3.141.59, Chrome browser version: 83.0.4103.116

Test data in .env file:
MAGENTO_BASE_URL=http://localhost/magento2/
MAGENTO_BACKEND_NAME=admin
MAGENTO_ADMIN_USERNAME=admin
MAGENTO_ADMIN_PASSWORD=admin123
BROWSER=chrome
MODULE_WHITELIST=Magento_Framework,Magento_ConfigurableProductWishlist,Magento_ConfigurableProductCatalogSearch

Under command prompt,I run the mftf test using the command:C:\xampp\htdocs\magento2\vendor\bin>mftf run:test AdminLoginTest

I am getting the below error as:
![UndefinedOffsetIssue](https://user-images.githubusercontent.com/43880097/87403851-01630e00-c5db-11ea-90f2-9a7c64fba34a.png)
![UndefinedOffsetIssue1](https://user-images.githubusercontent.com/43880097/87403855-032cd180-c5db-11ea-92ea-e5596ffcc49b.png)

PHPUnit\Framework\Exception Undefined offset: 43

Scenario --
ERROR

------------------------------------------------------------------------------------------------------------------------
15x DEPRECATION: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. C:\xampp\htdocs\magento2\vendor\symfony\event-dispatcher\EventDispatcher.php:58

 

Scenario Steps:

1. // Entering Action Group [loginAsAdmin] LoginAsAdmin

#1 C:\xampp\htdocs\magento2\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Codeception\Subscriber\Console.php:236
#2 C:\xampp\htdocs\magento2\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Codeception\Subscriber\Console.php:165
#3 C:\xampp\htdocs\magento2\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Codeception\Subscriber\Console.php:130
#4 C:\xampp\htdocs\magento2\vendor\symfony\event-dispatcher\EventDispatcher.php:264
#5 C:\xampp\htdocs\magento2\vendor\symfony\event-dispatcher\EventDispatcher.php:239
#6 C:\xampp\htdocs\magento2\vendor\symfony\event-dispatcher\EventDispatcher.php:73
#7 C:\xampp\htdocs\magento2\dev\tests\acceptance\tests\functional\Magento\FunctionalTest\_generated\default\AdminLoginTestCest.php:35
#8 Magento\AcceptanceTest\_default\Backend\AdminLoginTestCest->AdminLoginTest

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

**Comment by jilu1** [comment]
@rajateshr We have Jenkins builds for almost all branches and did not seem to have this issue. I think it maybe an environment or setup issue. Have you gone through steps documented in https://github.com/magento/magento2-functional-testing-framework/blob/develop/docs/getting-started.md before running the test?

**Comment by jilu1** [comment]
@rajateshr 
Feel free to reopen if you still has this issue.
