### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser

### ISSUE THREAD

**Issue by vinothkumar21** [magento/magento2-functional-testing-framework#758]
PHP Fatal error: Uncaught Error: Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser

Preconditions:
1. PHP version 7.2.30
2. Magento 2.3.4
3. MFTF 2.6.3
4. Selenium-server-standalone-3.141.59
5. Chrome browser version: 83.0.4103.116

Steps to reproduce:
1.Setup a Magento and MFTF version
2.Setting environment credentials in dev/test/acceptance/.env
3.Running vendor/bin/mftf build:project
4.Running vendor/bin/mftf generate:tests
5.Run a simple test by run : mftf run:test StorefrontUpdateWishlistTest --remove

![image](https://user-images.githubusercontent.com/68273134/87405108-9f0b0d00-c5dc-11ea-9884-562a2d64d5ad.png)

Expected result
MFTF-standalone can run a test with standard command line: bin/mftf run:test StorefrontUpdateWishlistTest --remove

Actual: 
Fatal error: Uncaught Error: Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser' not found in C:\xampp\htdocs\Magento\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Allure\Event\AddUniqueAttachmentEvent.php:76
Stack trace:
#0 C:\xampp\htdocs\Magento\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Allure\Event\AddUniqueAttachmentEvent.php(43): Magento\FunctionalTestingFramework\Allure\Event\AddUniqueAttachmentEvent->guessFileMimeType('C:\\Users\\emb-vi...')
#1 C:\xampp\htdocs\Magento\vendor\allure-framework\allure-php-api\src\Yandex\Allure\Adapter\Event\AddAttachmentEvent.php(35): Magento\FunctionalTestingFramework\Allure\Event\AddUniqueAttachmentEvent->getAttachmentFileName(Object(PHPUnit\Framework\ExceptionWrapper), NULL)
#2 C:\xampp\htdocs\Magento\vendor\allure-framework\allure-php-api\src\Yandex\Allure\Adapter\Allure.php(116): Yandex\Allure\Adapter\Event\AddAttachmentEvent->process(Object(Yandex\Allure\Adapter\Mo in C:\xampp\htdocs\Magento\vendor\magento\magento2-functional-testing-framework\src\Magento\FunctionalTestingFramework\Allure\Event\AddUniqueAttachmentEvent.php on line 76

**Comment by jilu1** [comment]
@vinothkumar21 Can you please check if this is fixed in MFTF 2.6.4?
