### ISSUE TITLE
Can not use MFTF 3.0 with Magento 2.4 + PHP 7.4

### ISSUE THREAD

**Issue by BavoJanss** [magento/magento2-functional-testing-framework#782]
@magento
I found the following issue when upgrading a Magento store to version 2.4. Magento strongly recommends running 2.4 on PHP 7.4. Luckily MFTF supports PHP 7.4 as of version 3.0.0. However Magento 2.4 requires **Elasticsearch** which in turn requires **symfony/finder** version ~4.0. However MFTF requires symfony/finder version ^5.0

So it looks like it is either not running on PHP 7.4 or not using MFTF anymore.
Any other way to fix this dependency problem?

**Comment by jilu1** [comment]
@BavoJanss Thank you for reporting the issue! I can see the dependency problem. I also found out that Magento composer.lock file has `symfony/finder` locked at version 5.1.2, which is what we have tested and seems work for us. Can you  try it?

**Comment by jilu1** [comment]
@BavoJanss Also can you give us the steps to reproduce the problem? This is problem because the symfony/finder dependency in Elasticsearch is in require-dev.

**Comment by jilu1** [comment]
@BavoJanss Let us know if you still has issue
