### ISSUE TITLE
MFTF tests creates a _generated directory in the root of the Magento project

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2-functional-testing-framework#801]
From @hostep:
> Is it expected that running the MFTF tests creates a `_generated` directory in the root of the Magento project? This feels incorrect to me, but I might be wrong ...
_Originally posted by @hostep in https://github.com/magento/magento2/pull/30107#issuecomment-697607579_

I really do agree with him that it shouldn't be generated in 3 different folders, as it shown in the https://github.com/magento/magento2/pull/30107

It also related to the https://github.com/magento/magento2-functional-testing-framework/issues/699

**Comment by jilu1** [comment]
@ihor-sviziev 
I cannot reproduce the case that mftf generates tests under _generated in the root of Magento project. Please send us the steps if this is still an issue.
The other two locations (from a link) are expected. One path is when mftf is run in standalone mode, the other path is when mftf is run in embedded mode.

**Comment by ihor-sviziev** [comment]
Hi @hostep,
Could you confirm that issue was already fixed?

**Comment by hostep** [comment]
Sorry for delay in answering @ihor-sviziev, still struggling through many mails after my holiday.

I believe @lfluvisotto was the one who reported it originally.

I never tried this out myself, I only based my comments on his report.

**Comment by jilu1** [comment]
Close issue. Feel free to reopen if this is still an issue.
