### ISSUE TITLE
Create individual product in test

### ISSUE THREAD

**Issue by sebastian-ehrling** [magento/magento2-functional-testing-framework#805]
I want to dynamically create a product in my mftf test. This works fine, but only with magento standard product attributes.
How is it possible to use individual product attributes in this case? 

### Preconditions
PHP 7.3
Magento 2.3.6
MFTF "~2.6.5"

### My MFTF Test:
.....
`<before>
<createData entity="testProductSwanHill" stepKey="testProductSwanHill"/>
</before>`
....

**My Testdata:**
`<entity name="testProductSwanHill" type="product">
        <data key="sku">726645ee7820cb177f2</data>
        <data key="type_id">simple</data>
        <data key="myattribute">Examplevalue</data>
        <data key="attribute_set_id">4</data>
        <data key="visibility">4</data>
        <data key="name">Swan Hill</data>
        <data key="price">80.00</data>
        <data key="urlKey" unique="suffix">72664</data>
        <data key="status">1</data>
        <data key="quantity">3</data>
        <data key="weight">1</data>
        <requiredEntity type="product_extension_attribute">EavStockItem</requiredEntity>
    </entity>`

**Comment by jilu1** [comment]
@sebastian-ehrling 
MFTF works for custom product attributes and they have to be setup through MFTF data and metadata. There are examples under Catalog module. I will close this issue and please feel free to reopen the issue if you have questions.
