### ISSUE TITLE
Getting issues when running the default testcases.

### ISSUE THREAD

**Issue by alwinj1989** [magento/magento2-functional-testing-framework#811]
Preconditions
1.  Magento 2.4.1
2. Magento Functional Testing Framework CLI 3.2.1.
3. PHP 7.4.12
4. Chrome 84.0.4147.105
5. Chromdriver version 84.0.4147.30
6. selenium-server-standalone-3.9.1.jar

Able to see the MFTF been setup correctly by running below command.
**vendor/bin/mftf doctor**

Reproducing the steps:
1. Start the selenium server.
2. Go to Magento root folder and run vendor/bin/mftf generate:tests AdminLoginSuccessfulTest -r

Expected result
Able to run the testcase for AdminLoginSuccessfulTest without any error

Actual result
   Showing the below error in the Terminal/Command prompt ::
DEPRECATION: Test VertexStorefrontRegisteredCustomerWithMassAddressesDefinedAddressValidationDuringCheckoutTest is missing required annotations.{"testName":"VertexStorefrontRegisteredCustomerWithMassAddressesDefinedAddressValidationDuringCheckoutTest","missingAnnotations":"title, description, severity"}
DEPRECATION: Test VertexStorefrontRegisteredCustomerAddressValidationDuringCheckoutProcessTest is missing required annotations.{"testName":"VertexStorefrontRegisteredCustomerAddressValidationDuringCheckoutProcessTest","missingAnnotations":"severity"}
NOTICE: 313 Section name violations detected. See mftf.log for details.[]
NOTICE: 764 section element name violations detected. See mftf.log for details.[]
NOTICE: 368 data entity name violations detected. See mftf.log for details.[]
NOTICE: 18 data entity key violations detected. See mftf.log for details.[]
NOTICE: 44 Page name violations detected. See mftf.log for details.[]
ERROR: 15 Suite(s) failed to generate. See mftf.log for details.
ERROR: 1 Test(s) failed to generate. See mftf.log for details.

Generate Tests Command Run (with errors)

Also attaching the MFTF log file too..
[mftf.log](https://github.com/magento/magento2-functional-testing-framework/files/5723856/mftf.log)

Also attaching the .env file(as txt file)
[env.txt](https://github.com/magento/magento2-functional-testing-framework/files/5723879/env.txt).

Please go through and let me know if there is any issue with MFTF with Magento2.4.1

**Comment by jilu1** [comment]
@alwinj1989 
The log shows you have this error
`ERROR: Unable to parse suite YotpoMultiStoreSuite  Single <actionGroup> node per xml file. 10 found in file: /home/alwin/Documents/projects/stage-spark-magetry/vendor/magento/module-data-services/Test/Mftf/ActionGroup/VerifyDsDataLayerActionGroup.xml  [] []
`
MFTF 3.x xml schema requires single entity per xml file. It looks like tests in some vendor bundle extensions are not properly updated. Can you try `vendor/bin/mftf upgrade:tests <path> --verbose` to update those tests and re-run generation?

**Comment by alwinj1989** [comment]
Hi @jilu1,

Thanks for looking into it. Tried to upgrade all the tests which were showing errors in the log but after doing it too we are getting the same things in the log file. It seems like the tests are not getting upgraded.

Just want to know is the above scenario is working for you?. If it is working then there are some things which I am doing wrong.

Many thanks,
Alwin Joseph

**Comment by jilu1** [comment]
@alwinj1989 
I knew there were tests problems in vendor bundle extensions in 2.4.1-p1 that we are currently working with. I think that's what you are seeing here. 
You can fix those tests manually or remove them in your local environment. You will not have the problem once upgrading to 2.4.1-p1.

**Comment by alwinj1989** [comment]
Thanks @jilu1  for the feedback. Will go through and will try my best to fix it. May I  know when 2.4.1-p1  will be released?. 

Many thanks,

**Comment by jilu1** [comment]
@alwinj1989 2.4.1-p1 GA in earlier February and earlier access mid January. Please check magento website for details.

**Comment by alwinj1989** [comment]
Hi @jilu1 ,

Thanks for the response. Also, able to solve the above issue.. Below are the following points which we think will be helpful for others too.

1. MFTF **doesn't work** properly with Magento/2.4.1 (B2B) version but works properly with the Magento/2.4.1 (Enterprise).
2. In order to solve the issue with B2B. Run the following command :- **vendor/bin/mftf upgrade:test vendor/magento/module-data-services/Test/Mftf/** 
3. After running the above command it will upgrade the test case for the specific module but the files which we get from this have some XML validation error due to some other special character. The file in which we got the error si the following i.e **vendor/magento/module-data-services/Test/Mftf/ActionGroup/VerifyDsDataLayerActionGroup/VerifyBaseDsDataLayerActionGroup.xml**.
4. Open it and remove the unwanted character. If you still get the error then please run the following command vendor/bin/mftf generate:test --debug=developer {{testcase}} -r (**note this will take some time to process around 2h or more**). It will let us know in which files the XML validation is getting failed.

General tips:
-----------------------
1. Running full test cases at once will take a lot of time. So, try to run the specific test cases that you need to debug.

Many thanks,
Alwin Joseph

**Comment by jilu1** [comment]
@alwinj1989 
Glad to see it worked out for you. Thanks for sharing the tips!
