### ISSUE TITLE
Feedback on page: /mftf/docs/getting-started.html

### ISSUE THREAD

**Issue by andriyShevtsov** [magento/magento2-functional-testing-framework#819]
Probably make sense to  add info about magento 2.4 instead 2.2. 

Find your version of MFTF. The latest Magento 2.3.x release supports MFTF 2.6.4. The latest Magento 2.2.x release supports MFTF 2.5.3.

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Logs, Errors]

**Comment by jilu1** [comment]
@andriyShevtsov 
When you open the **getting-started** page, you are seeing information for the latest MFTF 3.x which works for Magento 2.4.x. The callout section on top is for your reference when you need to find earlier versions.

I will close the issue and feel free to reopen if you think it's still confusing.
