### ISSUE TITLE
Php8 support

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2-functional-testing-framework#826]
As MFTF is one of the requirements for Magento 2 - as part of the php8 project we should add compatibility for MFTF.

```bash
~ composer why-not php 8

magento/magento2-functional-testing-framework  3.4.0   requires  php (^7.3)
csharpru/vault-php                             4.2.0   requires  php (^7.2)
doctrine/cache                                 v1.6.2  requires  php (~5.5|~7.0)
goaop/framework                                2.3.4   requires  php (~7.0)
```
- ❌ `csharpru/vault-php` there no available version with PHP 8 support https://github.com/CSharpRU/vault-php/issues/47
- ✔ `doctrine/cache` has PHP 8 support since version [1.10.1](https://packagist.org/packages/doctrine/cache#1.10.1)
- ❌ `goaop/framework` there no available version with PHP 8 support https://github.com/goaop/framework/issues/466

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Logs, Errors]

**Comment by jilu1** [comment]
@ihor-sviziev 
Thank you for your PR and just want to update you that we will have a epic related to PHP8 support. The work is on going.

**Comment by CSharpRU** [comment]
`csharpru/vault-php` updated with PHP8 support (4.2.1 tag)
